# Generated by Django 3.1.3 on 2021-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('auth_number', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
